URL_RAE = 'https://dle.rae.es/'
HTTP_HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}


ESPECIALIDADES = [
    'Acústica',
    'Aeronáutica',
    'Agricultura',
    'Alquimia',
    'Anatomía',
    'Antropología',
    'Arquitectura',
    'Arqueología',
    'Astrología',
    'Astronomía',
    'Biología',
    'Bioquímica',
    'Botánica',
    'Carpintería',
    'Cinegética',
    'Cinematografía',
    'Comercio',
    'Construcción',
    'Deportes',
    'Derecho',
    'Ecdótica',
    'Ecología',
    'Economía',
    'Electricidad, electrónica',
    'Equitación',
    'Escultura',
    'Esgrima',
    'Estadística',
    'Filosofía',
    'Física',
    'Fisiología',
    'Fonética, fonología',
    'Fotografía',
    'Geografía',
    'Geología',
    'Geometría',
    'Gramática',
    'Heráldica',
    'Imprenta',
    'Informática',
    'Ingeniería',
    'Lingüística',
    'Marina',
    'Matemáticas',
    'Mecánica',
    'Medicina',
    'Meteorología',
    'Métrica',
    'Milicia',
    'Mitología',
    'Música',
    'Numismática',
    'Óptica',
    'Ortografía',
    'Parapsicología',
    'Pintura',
    'Psicología',
    'Psiquiatría',
    'Química',
    'Religión',
    'Retórica',
    'Sociología',
    'Tauromaquia',
    'Tecnologías',
    'Telecomunicación',
    'Teoría literaria',
    'Topografía',
    'Transportes',
    'Televisión',
    'Urbanismo',
    'Veterinaria',
    'Zoología',
]

REGIONES = [
    'Álava',
    'Albacete',
    'Almería',
    'América',
    'América Central',
    'América Meridional',
    'Andalucía',
    'Antillas',
    'Aragón',
    'Argentina',
    'Asturias',
    'Ávila',
    'Badajoz',
    'Islas Baleares',
    'Bilbao',
    'Bolivia',
    'Burgos',
    'Cáceres',
    'Cádiz',
    'Canarias',
    'Cantabria',
    'Castilla',
    'Cataluña',
    'Colombia',
    'Córdoba',
    'Ciudad Real',
    'Costa Rica',
    'Cuenca',
    'Ecuador',
    'Estados Unidos',
    'El Salvador',
    'España',
    'Extremadura',
    'Filipinas',
    'Galicia',
    'Granada',
    'Gran Canaria',
    'Guadalajara',
    'Guatemala',
    'Guinea Ecuatorial',
    'Guipúzcoa',
    'Honduras',
    'Huelva',
    'Huesca',
    'Madrid',
    'Málaga',
    'La Mancha',
    'México',
    'Murcia',
    'Navarra',
    'Nicaragua',
    'Palencia',
    'Panamá',
    'Paraguay',
    'Perú',
    'Puerto Rico',
    'País Vasco',
    'República Dominicana',
    'Salamanca',
    'Segovia',
    'Sevilla',
    'Soria',
    'Teruel',
    'Toledo',
    'Uruguay',
    'Valencia',
    'Valladolid',
    'Venezuela',
    'Vizcaya',
    'Zamora',
    'Zaragoza',
]

CATEGORIAS_GRAMATICALES_ESPECIALES = {
    'verbo': ['transitivo', 'intransitivo', 'copulativo', 'impersonal', 'auxiliar', 'pronominal'],
    'sustantivo': ['masculino', 'femenino', 'neutro', 'plural'],
    'adjetivo': ['masculino', 'femenino', 'neutro', 'plural'],
    'adverbio': None,
    'preposición': None,
    'artículo': ['masculino', 'femenino', 'neutro', 'plural'],
    'conjunción': None,
    'pronombre': ['masculino', 'femenino', 'neutro', 'plural'],
}

COLOQUIAL = 'coloq.'
NO_USADAS = ('desus.', 'p. us.')

CLASES_QUE_PERTENECEN_A_LA_DEFINICION = ['etc.', 'núm. atóm.', 'U.', 'u.', 'p. ej.,', 'P. ej.,', 'U. t.', 'cm', 'cm,']
