# Generated by Django 4.1.7 on 2023-03-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('grammatical_category', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=10)),
                ('is_easy', models.BooleanField(default=False)),
                ('is_very_hard', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=100)),
                ('other_category', models.CharField(max_length=100)),
                ('is_colloquial', models.BooleanField()),
                ('is_pronominal', models.BooleanField()),
                ('is_plural', models.BooleanField()),
                ('use', models.CharField(max_length=10)),
                ('end_description', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('is_recursive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Encyclopedic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('is_easy', models.BooleanField(default=False)),
                ('is_very_hard', models.BooleanField(default=False)),
            ],
        ),
    ]
